"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require('express');
var router = express.Router();
var productPageController = require("../controllers/productPage.controller");
var productsController = require("../controllers/products.controller");
router.get('/', productsController.list);
router.get('/:productId', productPageController.productInfo);
router.get('/:productId/related', productPageController.productRelated);
router.get('/:productId/reviews', productPageController.productReviews);
exports.default = router;
