"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require('express');
var router = express.Router();
var searchController = require("../controllers/search.controller");
var productPageController = require("../controllers/productPage.controller");
router.get('/search', searchController.search);
router.get('/:productId', productPageController.productInfo);
router.get('/:productId/reviews', productPageController.productReviews);
exports.default = router;
