"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require('express');
var passport = require("passport");
var router = express.Router();
var userPageController = require("../controllers/user.controller");
router.get('/me', passport.authenticate('jwt', { session: false }), userPageController.getUserInfo);
router.put('/', passport.authenticate('jwt', { session: false }), userPageController.updateUserInfo);
router.post('/me/change_password', passport.authenticate('jwt', { session: false }), userPageController.updatePassword);
exports.default = router;
